version: "3.9"

x-test-framework: dotnet

services:
  tests:
    build: .
    command: dotnet test --logger "trx;LogFileName=$ENGI_WORKING_DIR/dotnet_test.trx" -r .
    volumes:
      - type: volume
        source: output
        target: $ENGI_WORKING_DIR
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
